export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR';
export const POST_CONTACT = 'POST_CONTACT';
export const POST_CONTACT_SUCCESS = 'POST_CONTACT_SUCCESS';
export const UPDATE_STORE = 'UPDATE_STORE'
export const POST_CONTACTS_ERROR = 'POST_CONTACTS_ERROR';